---
- tags: [basic]
  block:
    - name: Install basic command line tools
      package:
        name:
          - ripgrep
          - tree
          - htop
          - curl
          - wget
          - inotify-tools
          - ssh
          - gnupg
          - encfs
          - gparted
          - ecryptfs-utils
        state: present

    - name: Get language packages
      shell: check-language-support -l {{ lang }} | tr " " "\n"
      loop: [de, it, en]
      loop_control:
        loop_var: lang
      register: check_language_support

    - name: Install packages for languages
      package:
        name: "{{ check_language_support.results | map(attribute='stdout_lines') | flatten }}"
        state: present

    - name: Deinstall Qlipper
      package: name=qlipper state=absent

    - name: Configure the bash
      copy:
        src: configure_bash.sh
        dest: "{{ shell_conf_dir }}/bash"
        mode: 0700
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
