---
- tags: [basic]
  block:
    - name: Install basic command line tools
      apt: name={{ item }} state=present
      with_items:
        - tree
        - htop
        - curl
        - wget
        - apt-file
        - inotify-tools
        - nmap
        - ssh
        - gnupg
        - encfs
        - gparted
        - apache2-utils
        - mbr
        - rename

    - name: Monthly update of cache for apt-file
      cron:
        name: update apt-file
        job: apt-file update
        special_time: monthly

    - include: add_language_support.yml lang={{ item }}
      with_items: [ de, it, en ]

    - name: Deinstall Adobe Flash
      apt: package={{ item }} state=absent
      with_items:
        - adobe-flashplugin
        - flashplugin-installer

    - name: Deinstall Qlipper
      package: name=qlipper state=absent

    - name: Configure the bash
      copy:
        src: configure_bash.sh
        dest: "{{ shell_conf_dir }}/bash"
        mode: 0700
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Configure update-manager
      copy:
        src: release-upgrades
        dest: /etc/update-manager/release-upgrades

    - name: Disable the Caps Lock key
      replace:
        dest: /etc/default/keyboard
        regexp: XKBOPTIONS=""
        replace: XKBOPTIONS="ctrl:nocaps"
      register: keyboard_file

    - name: Apply change in keyboard configuration
      command: dpkg-reconfigure -f noninteractive keyboard-configuration
      when: keyboard_file.changed
