---
- name: Install packages for python
  apt: package={{ item }} state=present
  with_items:
    - python
    - python3
    - ipython
    - ipython3
    - python-pip
    - python3-pip

- name: Create IPython's config directory
  file:
    path: "{{ ipython_conf_dir }}"
    mode: 0700
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Configure IPython
  copy:
    src: ipython_config.py
    dest: "{{ ipython_conf_dir }}/ipython_config.py"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
