- hosts: main_computer
  roles:
    - media
    - os
    - programming
    - kulla.neovim
    - kulla.taskwarrior
    - vdirsyncer
    - khal
    - khard
    - asdf
    - docker
    - libvirt
    - gcloud
    - phpstorm
  tasks:
    - tags: [awesome]
      block:
        - name: Install awesome
          package:
            name:
              - awesome
              - awesome-extra
            state: present

    - tags: [firefox]
      block:
        - name: Install firefox
          package: name=firefox state=present

        - name: Backup firefox's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.mozilla/"

    - tags: [keepassxc]
      block:
        - name: Install keepassxc
          package: name=keepassxc state=present

        - name: Backup keepassxc's databases
          import_role: name=utils/dobackup
          vars:
                paths:
                  - "{{ user.homedir }}/keepassx/"
                exclude:
                  - "keepassx/*.kdb.lock"

    - tags: [sylpheed]
      block:
        - name: Install sylpheed
          package: name=sylpheed state=present

        - name: Backup sylpheed files
          import_role: name=utils/dobackup
          vars:
                paths:
                  - "{{ user.homedir }}/.sylpheed-2.0"
                  - "{{ user.homedir }}/Mail"

    - tags: [taskwarrior]
      block:
        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.task"

        - name: Show next tasks on terminal startup
          copy:
            src: show_tasks.sh
            dest: "{{ shell_conf_dir }}/bash"
            mode: 0700
            owner: "{{ user.name }}"
            group: "{{ user.group }}"

    - tags: [thunderbird]
      block:
        - name: Install thunderbird
          package: name=thunderbird state=present

        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.thunderbird"

    - tags: [work]
      block:
        - name: Install work tools
          package:
            state: present
            name:
              - gnuplot
              - texlive-latex-recommended
              - texlive-lang-german
              - texlive-publishers
              - texlive-bibtex-extra
              - biber
              - pstoedit
