- hosts: localhost
  roles:
    - { role: programming-environment, tags: [ programming-environment ] }
    - { role: os-basic, tags: [ os-basic ] }
    - { role: scientific-environment, tags: [scientific-environment] }
    - { role: serlo-workstation, tags: [serlo-workstation] }
    - { role: working-directories, tags: [working-directories] }
    - { role: birthday-reminder, tags: [birthday-reminder] }
    - { role: taskmanager, tags: [ taskmanager ] }
  vars:
    user:
      name: kulla
      group: kulla
      realname: Stephan Kulla
      homedir: /home/kulla
    git:
      email: git.mail@kulla.me
