- hosts: main_computer
  roles:
    - media
    - os
    - programming
    - messenger
    - web
    - job
    - kulla.taskwarrior
    - vdirsyncer
  tasks:
  - tags: [taskwarrior]
    block:
      - name: Backup taskwarrior's data location
        import_role: name=utils/dobackup
        vars:
          paths:
            - "{{ user.homedir }}/.task"

      - name: Show next tasks on terminal startup
        copy:
          src: show_tasks.sh
          dest: "{{ shell_conf_dir }}/bash"
          mode: 0700
          owner: "{{ user.name }}"
          group: "{{ user.group }}"
