- hosts: main_computer
  roles:
    - media
    - os
    - programming
    - messenger
    - web
    - job
    - taskwarrior
  vars:
    user:
      name: kulla
      group: kulla
      realname: Stephan Kulla
      homedir: /home/kulla
    git:
      email: git.mail@kulla.me
