- hosts: main_computer
  roles:
    - os
    - kulla.neovim
    - kulla.taskwarrior
    - vdirsyncer
    - khal
    - khard
    - asdf
    - docker
  tasks:
    - tags: [archive]
      block:
        - name: Install archive script
          copy:
            dest: /usr/local/bin
            mode: 0755
            src: archive

    - tags: [signal]
      block:
        - name: Install Signal Desktop
          community.general.snap:
            name: signal-desktop
            state: present

    - tags: [awesome]
      block:
        - name: Install awesome
          package:
            name:
              - awesome
              - awesome-extra
            state: present

    - tags: [bash-alias]
      block:
        - name: Install bash aliases
          copy:
            dest: "{{ shell_conf_dir }}/bash/aliases.sh"
            owner: "{{ user.name }}"
            group: "{{ user.group }}"
            mode: 0644
            content: |
              alias o='xdg-open'
              alias h='history'

    - tags: [firefox]
      block:
        - name: Install firefox
          community.general.snap:
            name: firefox
            state: present

        - name: Backup firefox's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.mozilla/"

    - tags: [keepassxc]
      block:
        - name: Install keepassxc
          package: name=keepassxc state=present

        - name: Backup keepassxc's databases
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/keepassx/"
            exclude:
              - "keepassx/*.kdb.lock"

    - tags: [media]
      block:
        - name: Install media player and codecs
          package:
            state: present
            name:
              - mplayer
              - ubuntu-restricted-addons
              - libavcodec-extra

        - name: Install tools for editing or creating media files
          package:
            state: present
            name:
              - audacity
              - inkscape
              - gimp
              - scrot
              - imagemagick
              - ffmpeg
              - graphviz
              - xournalpp

    - tags: [neovim]
      block:
        - name: Set default editor to neovim
          blockinfile:
            block: |
              export EDITOR=nvim
              export VISUAL=nvim
            marker_begin: Set default editor BEGIN
            marker_end: Set default editor END
            path: "{{ user.homedir }}/.bashrc"

        - name: Install coc settings file
          copy:
            src: coc-settings.json
            dest: "{{ neovim_config_dir }}"
            owner: "{{ user.name }}"
            group: "{{ user.group }}"
            mode: 0644

        - name: Alias for nvim
          blockinfile:
            block: |
              alias nvim='nvim -p'
            marker_begin: Alias for nvim BEGIN
            marker_end: Alias for nvim END
            path: "{{ user.homedir }}/.bashrc"

    - tags: [taskwarrior]
      block:
        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.task"

    - tags: [thunderbird]
      block:
        - name: Install thunderbird
          community.general.snap:
            name: thunderbird
            state: present

    - tags: [git, programming]
      block:
        - name: Install git
          package:
            name: git
            state: present

        - name: Install script "git update-main"
          copy:
            src: git-update-main
            dest: /usr/local/bin
            mode: 0555

        - name: Install script "git new-branch"
          copy:
            src: git-new-branch
            dest: /usr/local/bin
            mode: 0555

        - name: Create config directory for git
          file:
            path: "{{ git.config.dir }}"
            state: directory
            mode: 0700
            owner: "{{ user.name }}"
            group: "{{ user.group }}"

        - name: Configure git
          template:
            src: gitconfig
            dest: "{{ git.config.path }}"
            mode: 0o600
            owner: "{{ user.name }}"
            group: "{{ user.group }}"

    - tags: [working-directories]
      block:
        - name: Delete unneeded directores
          file: state=absent path={{ user.homedir }}/{{ item }}
          with_items:
            - Desktop
            - Downloads
            - Videos
            - Pictures
            - Public
            - Templates
            - Music
            - Documents

        - name: Configure working directories
          template:
            src: user-dirs.dirs
            dest: "{{ user.homedir }}/.config/user-dirs.dirs"
            owner: "{{ user.name }}"
            group: "{{ user.group }}"
            mode: 0600

        - name: Create tmpdir on startup and empty it
          cron:
            name: Empty tmpdir of current user
            special_time: reboot
            job: >
              mkdir -p "{{ user.tmpdir }}" &&
              chown "{{ user.name }}:{{ user.group }}" "{{ user.tmpdir }}" &&
              rm -rf "{{ user.tmpdir}}"/*

    - tags: [keyboard]
      block:
        # Note: A reboot is need to activate a change in the configuration
        - name: Configure keyboard
          ansible.builtin.blockinfile:
            path: /etc/default/keyboard
            insertafter: EOF
            block: |
              # Use capslock as compose key
              XKBOPTIONS="compose:caps"
