- hosts: localhost
  roles:
    - graphic-editing
    - basic-commandline-tools-available
    - programming-environment
    - scientific-environment
    - media-player
    - serlo-workstation
  vars:
    user:
      name: kulla
      group: kulla
      realname: Stephan Kulla
      homedir: /home/kulla
    git:
      email: git.mail@kulla.me
