- hosts: main_computer
  vars:
    asdf_install_dir: "{{ user.homedir }}/.local/share/asdf"
  roles:
    - media
    - os
    - programming
    - messenger
    - web
    - job
    - kulla.taskwarrior
    - vdirsyncer
    - khal
  tasks:
    - tags: [taskwarrior]
      block:
        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.task"

        - name: Show next tasks on terminal startup
          copy:
            src: show_tasks.sh
            dest: "{{ shell_conf_dir }}/bash"
            mode: 0700
            owner: "{{ user.name }}"
            group: "{{ user.group }}"

    - tags: [keepassxc]
      block:
        - name: Install keepassxc
          package: name=keepassxc state=present

        - name: Backup Keepassxc's databases
          import_role: name=utils/dobackup
          vars:
                paths:
                  - "{{ user.homedir }}/keepassx/"
                exclude:
                  - "keepassx/*.kdb.lock"

    - tags: [awesome]
      block:
        - name: Install awesome
          package:
            name:
              - awesome
              - awesome-extra
            state: present

    - tags: [asdf]
      block:
        - name: Create directory for asdf
          file:
            path: "{{ asdf_install_dir }}"
            state: directory
            recurse: yes
            owner: "{{ user.name }}"
            group: "{{ user.group }}"
            mode: 0o775

        - name: Install asdf version manager
          git:
            repo: https://github.com/asdf-vm/asdf.git
            version: v0.7.4
            dest: "{{ asdf_install_dir }}"
            update: no
            clone: yes
