- hosts: localhost
  roles:
    - os-basic
    - programming-environment
    - scientific-environment
    - serlo-workstation
    - feedreader
    - mailclient
  vars:
    user:
      name: kulla
      group: kulla
      realname: Stephan Kulla
      homedir: /home/kulla
    git:
      email: git.mail@kulla.me
