- hosts: main_computer
  roles:
    - media
    - os
    - programming
    - kulla.neovim
    - kulla.taskwarrior
    - vdirsyncer
    - khal
    - khard
    - asdf
    - docker
    - libvirt
    - gcloud
    - phpstorm
  tasks:
    - tags: [awesome]
      block:
        - name: Install awesome
          package:
            name:
              - awesome
              - awesome-extra
            state: present

    - tags: [firefox]
      block:
        - name: Install firefox
          package: name=firefox state=present

        - name: Backup firefox's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.mozilla/"

    - tags: [keepassxc]
      block:
        - name: Install keepassxc
          package: name=keepassxc state=present

        - name: Backup keepassxc's databases
          import_role: name=utils/dobackup
          vars:
                paths:
                  - "{{ user.homedir }}/keepassx/"
                exclude:
                  - "keepassx/*.kdb.lock"

    - tags: [media]
      block:
        - name: Install media player and codecs
          package:
            state: present
            name:
              - mplayer
              - ubuntu-restricted-addons
              - libavcodec-extra

        - name: Install tools fo editing media files
          package:
            state: present
            name:
              - audacity
              - inkscape
              - gimp
              - scrot
              - imagemagick
              - ffmpeg
              - graphviz

    - tags: [neovim]
      block:
        - name: Set default editor to neovim
          blockinfile:
            block: |
              export EDITOR=nvim
              export VISUAL=nvim
            marker_begin: Set default editor BEGIN
            marker_end: Set default editor END
            path: "{{ user.homedir }}/.bashrc"

        - name: Install coc settings file
          template:
            src: coc-settings.json
            dest: "{{ neovim_config_dir }}"
            owner: "{{ user.name }}"
            group: "{{ user.group }}"
            mode: 0644

        - name: Alias for nvim
          blockinfile:
            block: |
              alias nvim='nvim -p'
            marker_begin: Alias for nvim BEGIN
            marker_end: Alias for nvim END
            path: "{{ user.homedir }}/.bashrc"

    - tags: [sylpheed]
      block:
        - name: Install sylpheed
          package: name=sylpheed state=present

        - name: Backup sylpheed files
          import_role: name=utils/dobackup
          vars:
                paths:
                  - "{{ user.homedir }}/.sylpheed-2.0"
                  - "{{ user.homedir }}/Mail"

    - tags: [taskwarrior]
      block:
        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.task"

    - tags: [thunderbird]
      block:
        - name: Install thunderbird
          package: name=thunderbird state=present

        - name: Backup taskwarrior's data location
          import_role: name=utils/dobackup
          vars:
            paths:
              - "{{ user.homedir }}/.thunderbird"

    - tags: [work]
      block:
        - name: Install work tools
          package:
            state: present
            name:
              - gnuplot
              - texlive-latex-recommended
              - texlive-lang-german
              - texlive-publishers
              - texlive-bibtex-extra
              - biber

        - name: Install script "repo-update"
          copy:
            src: repo-update
            dest: /usr/local/bin
            mode: 0555

    - tags: [work, serlo, poedit]
      block:
        - name: Install poedit
          snap:
            name: poedit

    - tags: [work, terraform]
      block:
        - name: Add apt-key for hashicorp
          apt_key:
            url: "https://apt.releases.hashicorp.com/gpg"
            state: present

        - name: Add hashicorp repository
          apt_repository:
            repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
            state: present
            update_cache: true
            filename: hashicorp

        - name: Install terraform-ls
          package:
            name: terraform-ls
            state: present

    - tags: [work, cloudflare]
      block:
        - name: Install cloudflared
          apt:
            deb: https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
            state: present

    - tags: [ youtube-dl ]
      block:
        - name: Install youtube-dl
          get_url: url=http://yt-dl.org/latest/youtube-dl
                   dest=/user/local/bin/youtube-dl
                   mode=0755

        - name: Weekly update of youtube-dl
          cron:
            name: update youtube-dl
            job: youtube-dl --update
            special_time: weekly
