- hosts: localhost
  roles:
    - { role: programming-environment, tags: [ programming-environment ] }
    - { role: os-basic, tags: [ os-basic ] }
    - scientific-environment
    - serlo-workstation
    - working-directories
    - birthday-reminder
    - { role: taskmanager, tags: [ taskmanager ] }
  vars:
    user:
      name: kulla
      group: kulla
      realname: Stephan Kulla
      homedir: /home/kulla
    git:
      email: git.mail@kulla.me
