- hosts: localhost
  roles:
    - graphic-editing
    - basic-commandline-tools-available
    - programming-environment
    - scientific-environment
  vars:
    user:
      name: kulla
      realname: Stephan Kulla
    git:
      email: git.mail@kulla.me
