#!/bin/bash
#
# Utility functions for backups.

CMD="$1"                        # command given via command line argument
DEFAULT_CMD="run"               # default command
MOUNT_DIR="{{ mntdir }}"        # mount point for backup disk
MAPPER=$(basename "$MOUNT_DIR") # name for mapper device

# device ids for backup disks
DEVICE_IDS="""
scsi-SPI-239_USB_2.0_Drive_S24QJ9AC603190
scsi-SPI-239_USB_2.0_Drive_S24QJ9EC604225
usb-ST350083_0AS_95B1EFFFFFFF-0:0
756db0a1-b1ee-44eb-a158-8950d175a8d5
ata-ST500LM011_HM501II_S24QJ9AC603190
0b24047e-a9bd-4409-bc0c-8bc067d05898
"""

###
# Returns with exist status zero, iff the backup disk is mounted.
###
function backup_disk_is_mounted() {
	mountpoint -q "$MOUNT_DIR"
}

###
# Mounting the backup disk.
###
function mount_backup_disk() {
	if ! backup_disk_is_mounted; then
		for DEVICE_ID in $DEVICE_IDS; do
			DEVICE="/dev/disk/by-uuid/${DEVICE_ID}"

			if [ -e "$DEVICE" ]; then
				sudo cryptsetup luksOpen "$DEVICE" "$MAPPER" && \
				sudo mount -t ext4 "/dev/mapper/${MAPPER}" "$MOUNT_DIR"

				break
			fi
		done
	fi

	backup_disk_is_mounted
}

###
# Umounting the backup disk.
#
function umount_backup_disk() {
	if [ -n "$(mount -l | grep "$MOUNT_DIR")" ]; then
		sudo umount "$MOUNT_DIR" && \
		sudo cryptsetup close "$MAPPER"
	fi

	! backup_disk_is_mounted
}

###
# Show help message.
###
function show_help() {
	echo """backup [cmd]

help   - show this help
mount  - mount backup disc
umount - umount backup disc"""
}

if [ -z "$CMD" ]; then
	CMD="$DEFAULT_CMD"
fi

if [ "$CMD" == "mount" ]; then
	mount_backup_disk
elif [ "$CMD" == "umount" ]; then
	umount_backup_disk
elif [ "$CMD" == "help" ]; then
	show_help
fi
