---
- tags: [shell]
  block:
    - name: Install default shell
      apt: package=bash state=present

    - name: Create configure directories for bash
      file:
        path: "{{ shell_conf_dir }}/{{ item.name }}"
        state: directory
        mode: 0700
        owner: "{{ user.name }}"
        group: "{{ user.group}}"
      with_items: "{{ shell_rc_targets }}"

    - name: Install files for loading shell configurations
      template:
        src: configure.sh
        dest: "{{ shell_conf_dir }}/configure_{{ item.name }}.sh"
        mode: 0700
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
      with_items: "{{ shell_rc_targets }}"

    - name: Add shell configuration loading into default shell configuration files
      lineinfile:
        line: "source '{{ shell_conf_dir }}/configure_{{ item.name }}.sh'"
        dest: "{{ item.fromfile }}"
      with_items: "{{ shell_rc_targets }}"
