---
- name: Install necessary tools for tum-workstation
  apt: name={{ item }} state=present
  with_items:
    - cifs-utils
    - xournal

- name: Download client for LRZ Sync and Share
  get_url:
    url: https://syncandshare.lrz.de/client_deployment/LRZ_Sync_Share_Latest_amd64.deb
    dest: /opt/lrz_sync_and_share_latest_amd64.deb

- name: Install LRZ Sync and Share.
  apt: deb=/opt/lrz_sync_and_share_latest_amd64.deb state=present

- name: Umount NAS filer (when they already exist)
  command: umount {{ nas.mntdir }}/{{ item.target }}
  with_items: "{{ nas.targets }}"
  ignore_errors: True

- name: Create mount points for NAS filer
  file:
    path: "{{ nas.mntdir }}/{{ item.target }}"
    state: directory
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items: "{{nas.targets}}"

- name: Create credential file for mounting the NAS filer
  template: src=credential_file dest={{ nas.mntdir }}/.credentials mode=0600

- name: Mount personal NAS filer
  mount:
    state: present
    fstype: cifs
    name: "{{ nas.mntdir }}/{{ item.target }}"
    src: //nas.ads.mwn.de/{{ item.src }}
    opts: credentials={{ nas.mntdir }}/.credentials,uid={{ user.name }},gid={{ user.group}},rw,noserverino,noauto
  with_items: "{{nas.targets}}"
