#!/bin/bash

function run_xrandr() {
	xrandr --output "LVDS-1" --fb $1 --panning $1 --scale-from $1
}

if [[ $1 == "1080p" ]]; then
	run_xrandr "1920x1157"
elif [[ $1 == "720p" ]]; then
	run_xrandr "1280x797"
elif [[ $1 == "" ]]; then
	run_xrandr "1366x768"
else
	echo "Wrong Argument!" 1 >& 2
	exit 1
fi
