---
- tags: [ xournal ]
  block:
    - name: Install xournal
      package: name=xournal state=present

    - name: Configure xournal
      copy:
        src: config
        dest: "{{ user.homedir }}/.xournal/config"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
