---
- tags: [taskwarrior]
  block:
    - name: Install tool taskwarrior
      apt: package={{ item }} state=present
      with_items:
        - taskwarrior
        - tasksh

    - name: Include taskwarrior configuration
      include_vars: taskrc.yml
      no_log: true

    - name: Configure taskwarrior
      template:
        src: taskrc
        dest: "{{ user.homedir}}/.taskrc"
        mode: 0600
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Create directory for taskserver certificates
      file:
        path: "{{ taskserver_certificates_dir }}"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        state: directory

    - name: Copy certificates for taskserver
      copy:
        src: "{{ item }}"
        dest: "{{ taskserver_certificates_dir }}"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        mode: 0400
      with_items:
        - ca.cert.pem
        - my.cert.pem
        - key.pem

    - name: Cron job for syncing taskwarrior
      cron:
        name: sync taskwarrior
        job: task sync
        user: "{{ user.name }}"
        special_time: hourly

    - name: Show next tasks on terminal startup
      copy:
        src: show_tasks.sh
        dest: "{{ shell_conf_dir }}/bash"
        mode: 0700
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
