---
- tags: [vdirsyncer]
  block:
    - name: Install vdirsyncer
      package: name=vdirsyncer state=present

    - name: Create config directory for vdirsyncer
      file:
        path: "{{ vdirsyncer_config_dir }}"
        state: directory
        mode: 0700
        owner: "{{ user.name }}"

    - name: Configure vdirsyncer
      template:
        src: vdirsyncer_config
        dest: "{{ vdirsyncer_config_dir }}/config"
        mode: 0400
        owner: "{{ user.name }}"
