---
- name: Install Pyenv from git repo
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_install_dir }}"

- name: Install pyenv-virtualenv plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ virtualenv_install_dir }}"

- name: Change owner and group of pyenv and virtualenv directory
  file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: yes
  with_items:
    - "{{ pyenv_install_dir }}"
    - "{{ virtualenv_install_dir }}"

- name: Define evironment variables for Pyenv
  template:
    src: configure_pyenv.sh
    dest: "{{ shell_conf_dir }}/profile"
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
