---
- tags: [phpstorm]
  block:
    - name: Install phpstorm
      snap:
        name:
          - phpstorm
        classic: yes

    - name: Ignore .idea directories in git
      blockinfile:
        path: "{{ git_global_ignore_file }}"
        block: .idea
        marker: "# {mark} configuration for phpstorm"
