- tags: [asdf, programming]
  block:
    - name: Create temporary file for downloading asdf
      ansible.builtin.tempfile:
        state: file
        suffix: .tar.gz
      register: asdf_download

    - name: Download asdf relase tarball
      ansible.builtin.get_url:
        url: https://github.com/asdf-vm/asdf/releases/download/v0.18.1/asdf-v0.18.1-linux-amd64.tar.gz
        dest: "{{ asdf_download.path }}"
        checksum: md5:6c68f29f7cf16bf4a0cd2d50f464ccf0

    - name: Extract asdf executable
      ansible.builtin.unarchive:
        remote_src: yes
        src: "{{ asdf_download.path }}"
        dest: /usr/local/bin/asdf
        include: [asdf]
        mode: 0o555

    - name: Configure asdf
      template:
        src: configure_asdf.sh
        dest: "{{ shell_conf_dir }}/bash"
        mode: 0o700
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Install dev-tools for python
      package:
        name:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: present
