---
- name: Install basic command line tools
  apt: name={{ item }} state=present
  with_items:
    - tree
    - htop
    - curl
    - wget
    - apt-file
    - inotify-tools
    - nmap
    - ssh
    - gnupg
    - gparted

- name: Update cache for apt-file
  command: apt-file update
  args:
    creates: /var/cache/apt/apt-file/*
