---
- include: basic_commandline_tools_available.yml
- include: xmonad.yml

- name: Deinstall Adobe Flash
  apt: package={{ item }} state=absent
  with_items:
    - adobe-flashplugin
    - flashplugin-installer

- name: Configure the bash
  copy:
    src: configure_bash.sh
    dest: "{{ shell_conf_dir }}/bash"
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- include: add_language_support.yml lang={{ item }}
  with_items: [ de, it, en ]
