" Turn on line numbering. Turn it off with "set nonu"
set nu

" Set syntax on
syntax on

" http://superuser.com/questions/494115/vim-indent-in-latex-align-goes-crazy
let g:tex_indent_brace = 0

" Indent automatically depending on filetype
filetype indent plugin on
set autoindent

" Case insensitive search
set ic

" Change directory of .swp files
set directory=~/.vim/tmp

" Higlhight search
set hls

" Wrap text instead of being on one line
set lbr
set linebreak nolist
set display+=lastline

" Set terminal background to be dark
set background=dark

" Remap keys so that vim behaves more like normal text editors
noremap  <buffer> <silent> <Up>   gk
noremap  <buffer> <silent> <Down> gj
noremap  <buffer> <silent> <Home> g<Home>
noremap  <buffer> <silent> <End>  g<End>
inoremap <buffer> <silent> <Up>   <C-o>gk
inoremap <buffer> <silent> <Down> <C-o>gj
inoremap <buffer> <silent> <Home> <C-o>g<Home>
inoremap <buffer> <silent> <End>  <C-o>g<End>

" Show ruler at 80 characters
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

" == Tabs ==

set shiftwidth=4               " use 4 spaces for (>>) and (<<) operator
set tabstop=4                  " 1 tab = 4 spaces
set list                       " highlight tabs
set listchars=tab:>.,trail:%   " ">..." for tabs and "%" for trailing spaces
highlight SpecialKey ctermfg=7 " set highlight color for tabs to light gray


" == My key bindings ==

nmap <C-A> :w<CR>
imap <C-A> <ESC>:w<CR>i
nmap <C-X> :q<CR>
imap <C-X> <ESC>:q<CR>

" == Handling of filetypes ==

" Set file type of scons files to python
au BufRead,BufNewFile Sconstruct setfiletype python
au BufRead,BufNewFile Sconscript setfiletype python

" === Python ===
autocmd Filetype python setlocal expandtab

" === Tex ===
autocmd Filetype tex setlocal expandtab
autocmd Filetype tex setlocal tabstop=2
autocmd Filetype tex setlocal shiftwidth=2
autocmd Filetype tex setlocal spell spelllang=en
autocmd Filetype tex setlocal colorcolumn=

" === Haskell ===
au BufRead,BufNewFile *.cabal setlocal expandtab
autocmd Filetype haskell setlocal expandtab
autocmd Filetype hamlet  setlocal expandtab

" === Markdown ===
au BufRead,BufNewFile *.md setfiletype markdown
autocmd Filetype markdown setlocal expandtab
autocmd Filetype markdown setlocal colorcolumn=

" === YAML ===
au BufRead,BufNewFile *.yml setfiletype yaml
autocmd Filetype yaml setlocal expandtab
autocmd Filetype yaml setlocal tabstop=2
autocmd Filetype yaml setlocal shiftwidth=2
autocmd Filetype yaml setlocal foldmethod=expr
autocmd Filetype yaml setlocal foldlevel=1000
autocmd Filetype yaml setlocal foldexpr=match(getline(v:lnum),'[^[:space:]\-]')
