---
rsnapshot_conf_file: /etc/rsnapshot.conf
rsnapshot_conf_dir: /etc/rsnapshot
rsnapshot_backup_conf: backups.conf
rsnapshot_exclude_conf: excluded_files_special
rsnapshot_include_conf: included_files_special

retains:
  - name: hourly
    times: 6
    min_time_diff: 0
  - name: daily
    times: 7
    min_time_diff: 60 * 60 * 12
  - name: weekly
    times: 4
    min_time_diff: 60 * 60 * 24 * 6
  - name: monthly
    times: 6
    min_time_diff: 60 * 60 * 24 * 28

backup_mntdir: /media/backupfestplatte
backup_dir: "{{ backup_mntdir }}/rsnapshot/"
backup_script: /usr/local/bin/backup
backup_conf: "{{ rsnapshot_conf_dir }}/{{ rsnapshot_backup_conf }}"
backup_exclude_conf: "{{ rsnapshot_conf_dir }}/{{ rsnapshot_exclude_conf }}"
backup_include_conf: "{{ rsnapshot_conf_dir }}/{{ rsnapshot_include_conf }}"
