---
- tags: [ programming ]
  block:
    - name: Install basic programming tools
      package:
        state: present
        name:
          - make
          - git
          - gource

    - name: Configure git
      template:
        src: gitconfig
        dest: "{{ user.homedir }}/.gitconfig"
        mode: 0o600
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Create global gitignore file
      file:
        path: "{{ git_global_ignore_file }}"
        state: touch
        mode: 0o400
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
