---
- tags: [ programming ]
  block:
    - name: Install basic programming tools
      package:
        state: present
        name:
          - make
          - git
          - gource

    - name: Configure git
      template:
        src: gitconfig
        dest: "{{ user.homedir }}/.gitconfig"
        mode: 0600
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
