---
- tags: [science]
  block:
    - name: Install basic scientific tools
      package:
        state: present
        name:
          - gnuplot
          - texlive-latex-recommended
          - texlive-lang-german
          - texlive-publishers
          - texlive-bibtex-extra
          - biber
          - pstoedit
