user:
  name: kulla
  group: kulla
  realname: Stephan Kulla
  homedir: /home/kulla
git:
  email: git.mail@kulla.me

neovim_user_id: "{{ user.name }}"
neovim_configuration: "{{ lookup('file', 'neovim_configuration.vim') }}"
neovim_plugins:
  - name: neoclide/coc.nvim
    options:
      branch: release
  - name: neoclide/coc-eslint
    options:
      do: yarn install --frozen-lockfile
  - name: neoclide/coc-git
    options:
      do: yarn install --frozen-lockfile
  - name: neoclide/coc-json
    options:
      do: yarn install --frozen-lockfile
  - name: neoclide/coc-prettier
    options:
      do: yarn install --frozen-lockfile
  - name: neoclide/coc-tsserver
    options:
      do: yarn install --frozen-lockfile
  - name: neoclide/coc-yank
    options:
      do: yarn install --frozen-lockfile
  - name: fannheyward/coc-rust-analyzer
    options:
      do: yarn install --frozen-lockfile
  - tpope/vim-fugitive
  - bogado/file-line
  - name: nvim-treesitter/nvim-treesitter
    options:
      do: :TSUpdate
  - https://gitlab.com/HiPhish/rainbow-delimiters.nvim.git
  - nvim-treesitter/nvim-treesitter-context
  - navarasu/onedark.nvim
  - itchyny/lightline.vim
  - robitx/gp.nvim

taskwarrior_user_id: "{{ user.name }}"
taskwarrior_cronjob_sync: true
taskwarrior_ca_certificate: taskwarrior_server.cert.pem
taskwarrior_client_certificate: taskwarrior_client.cert.pem
taskwarrior_client_key: taskwarrior_client.key.pem
taskwarrior_configuration: |
  {{ taskwarrior_taskd_configuration }}
  {{ lookup('file', 'taskwarrior_configuration.rc') }}
