user:
  name: kulla
  group: kulla
  realname: Stephan Kulla
  homedir: /home/kulla
git:
  email: git.mail@kulla.me

neovim_user_id: "{{ user.name }}"
neovim_configuration: "{{ lookup('file', 'neovim_configuration.vim') }}"
neovim_plugins:
  - vim-airline/vim-airline
  - morhetz/gruvbox
  - name: neoclide/coc.nvim
    options:
      branch: release
  - pangloss/vim-javascript
  - leafgarland/typescript-vim
  - peitalin/vim-jsx-typescript
  - name: styled-components/vim-styled-components
    options:
      branch: main
  - jparise/vim-graphql

taskwarrior_user_id: "{{ user.name }}"
taskwarrior_cronjob_sync: true
taskwarrior_ca_certificate: taskwarrior_server.cert.pem
taskwarrior_client_certificate: taskwarrior_client.cert.pem
taskwarrior_client_key: taskwarrior_client.key.pem
taskwarrior_configuration: |
  {{ taskwarrior_taskd_configuration }}
  {{ lookup('file', 'taskwarrior_configuration.rc') }}
