---
- tags: [ youtube-dl ]
  block:
    - name: Check if youtube-dl is already installed
      stat: path={{ youtubedl_executable_path }}
      register: youtubedl_bin

    - name: Install youtube-dl
      get_url: url=http://yt-dl.org/latest/youtube-dl
               dest={{ youtubedl_executable_path }}
               mode=0755
               force=yes
      when: not youtubedl_bin.stat.exists

    - name: Install script for updating youtube-dl
      copy:
        src: youtube-dl-update
        dest: /etc/cron.weekly
        mode: 0544
