---
- name: Install vim
  apt: package={{ text_editor }} state=present

- name: Configure vim
  copy:
    src: vimrc
    dest: "{{ user.homedir}}/.vimrc"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Create directory for .swp files
  file:
    path: "{{ user.homedir}}/.vim/tmp"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700

- name: Make vim the default text editor
  template:
    src: set_default_text_editor.sh
    dest: "{{ shell_conf_dir }}/profile"
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install gedit with plugins
  apt: package={{ item }} state=present
  with_items:
    - gedit
    - gedit-plugins
