---
dependencies:
  - basic-commandline-tools-available
  - text-editor
  - { role: graphic-editing, tags: [graphic-editing] }
  - { role: audio-editing, tags: [audio-editing] }
  - media-player
  - password-manager
  - mailclient
  - feedreader
  - webbrowser
  - shell
  - role: dobackup
    paths:
      - "{{ user.homedir }}/.ssh"
      - "{{ user.homedir }}/.gnupg"
  - { role: bash-alias, alias: o, cmd: xdg-open }
  - { role: bash-alias, alias: h, cmd: history }
