#!/bin/bash

BASE_TARGET_DIR=$HOME/archive

function error() {
	echo "ERROR: $*" >&2
	exit 1
}

function info() {
	echo "INFO: $*" >&2
}

function archive_file() {
	FILE="$1"
	FILE_NAME="$2"
	FILE_DATE="$3"

	FILE_REALPATH=$(realpath "$FILE")

	if [ ! -e "$FILE_REALPATH" ]; then
		error "File '$FILE' does not exist"
	fi

	if [ -z "$FILE_NAME" ]; then
		FILE_NAME=$(basename "$FILE_REALPATH")
	fi

	if [ -z "$FILE_DATE" ]; then
		FILE_DATE="@$(stat --format='%Y' "$FILE_REALPATH")"
	fi

	YEAR=$(date --date="$FILE_DATE" '+%Y') || \
			error "Date '$FILE_DATE' cannot be parsed"
	DATE_PREFIX=$(date --date="$FILE_DATE" '+%Y-%m-%d') || \
			error "Date '$FILE_DATE' cannot be parsed"

	TARGET="$BASE_TARGET_DIR/$YEAR/$DATE_PREFIX-$FILE_NAME"
	TARGET_DIRNAME=$(dirname "$TARGET")

	if [ ! -e "$TARGET_DIRNAME" ]; then
		info "Create directory '$TARGET_DIRNAME'"
		mkdir -p "$TARGET_DIRNAME"
	fi

	info "Archiving '"$FILE"' -> '$TARGET'"
	mv "$FILE" "$TARGET" || error "Error while archiving '$FILE'"
	info "Done. Undo: mv '$TARGET' '$FILE_REALPATH'"
}

# Read all arguments and archive files
while [ "$#" -gt 0 ]; do
	case "$1" in
		-d) ARG_DATE="$2"; shift 2;;
		-n) ARG_NAME="$2"; shift 2;;
		*) archive_file "$1" "$ARG_NAME" "$ARG_DATE"; ARG_NAME=""; shift 1;;
	esac
done
