---
- name: Install the tool when
  apt: package=when state=present

- name: Configure tool when
  template:
    src: when_preferences
    dest: "{{ user.homedir }}/.when/preferences"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Show next birthdays on starting of a terminal
  copy:
    src: show_birthdays.sh
    dest: "{{ shell_conf_dir }}/bash"
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
