---
- tags: [xmonad]
  block:
    - name: Install xmonad
      apt: package={{ item }} state=present
      with_items:
        - xmonad
        - suckless-tools

    - name: Create configuration directory for xmonad
      file:
        path: "{{ xmonad_conf_dir }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.group }}"

    - name: Configure xmonad
      copy:
        src: xmonad.hs
        dest: "{{ xmonad_conf_dir }}/xmonad.hs"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
